particlesJS("particles-js",{
  particles:{
    number:{value:180},
    color:{value:["#38bdf8","#00f7ff","#22d3ee"]},
    shape:{type:"circle"},
    opacity:{value:0.7},
    size:{value:2},
    line_linked:{
      enable:true,
      distance:120,
      color:"#38bdf8",
      opacity:0.4,
      width:1
    },
    move:{
      enable:true,
      speed:1.2
    }
  }
});
